spring.application.name=guilds-warriors
spring.datasource.url=jdbc:mysql://localhost:3306/warriorsdb
spring.datasource.username=root
spring.datasource.password=younes123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always